version: '3'

volumes:
    data: {}
services:
    mariadb:
        container_name: mariadb
        restart: always
        expose:
            - "3306"
    nginx:
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
    wordpress:
        container_name: wordpress
        restart: always
        volumes:
            - data:/var/www/html
        expose:
            - "9000"
