version: '3.3'

services:
    nginx:
        container_name: nginx
        build: requirements/nginx
        hostname: localhost
        volumes:
           - wp:/var/www/html
        networks:
           - app-network
        ports:
           - "443:443"
        depends_on:
           - wordpress
        restart: always
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        hostname: localhost
        volumes:
           - db:/var/lib/mysql
        environment:
           DB_NAME: ${DB_NAME}
           DB_USER: ${DB_USER}
           DB_PASSWORD: ${DB_PASSWORD}
           DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
           - app-network
        restart: always
    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        hostname: localhost
        volumes:
           - wp:/var/www/html
        environment:
           DB_HOST: ${DB_HOST}
           DB_NAME: ${DB_NAME}
           DB_USER: ${DB_USER}
           DB_PASSWORD: ${DB_PASSWORD}
           DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
           ADMIN_USER: ${ADMIN_USER}
           ADMIN_EMAIL: ${ADMIN_EMAIL}
           USER_EMAIL: ${USER_EMAIL}
           DOMAIN_NAME: ${DOMAIN_NAME}
           TITLE: ${TITLE}
        networks:
           - app-network
        depends_on:
           - mariadb
        restart: always

volumes:
    db:
         driver: local
         driver_opts:
            type: none
            o: bind
            device: /home/tsekiguc/data/db
    wp:
         driver: local
         driver_opts:
            type: none
            o: bind
            device: /home/tsekiguc/data/wp
networks:
    app-network:
        driver: bridge
